pull_request_rules:
  - name: Automatic merge
    conditions:
        - or:
            # own PR or backport from mergify
            - author=damien-devpy
            - and:
                - author=mergify
                - base~=^mergify/.*
    actions:
      merge:
        method: squash

  - name: auto backport to BI branch
    conditions:
        - author=damien-devpy
    actions:
      backport:
        branches:
            - bi

  - name: delete branch after merge
    conditions:
        - merged
    actions:
      delete_head_branch:
